"""nginx 配置维护 (B5 host-based 域名映射)

约定:
- map 文件路径: settings.NGINX_SITES_MAP (默认 /etc/nginx/conf.d/sites.map)
- 与 nginx 容器共享 named volume nginx_conf
- nginx 容器内 inotify 监听 sites.map 变化, 自动 `nginx -s reload`

API:
- rebuild_sites_map(db)  从 DB 重新生成整个 map
    调用时机: 应用启动 (lifespan) + 任何 add/remove domain 后 (显式)
"""
import logging
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.models.site import Site, SiteDomain

logger = logging.getLogger(__name__)


def _format_map(items: list[tuple[SiteDomain, str]]) -> str:
    """生成 map 文件内容.

    参数: list of (SiteDomain, slug) 元组, 避免访问 ORM 关系触发 lazy IO.

    格式: <domain> <slug>; (分号是语句结束符, value 不带分号)
    带注释头 (说明 + 时间戳).
    """
    lines = [
        "# Auto-generated by ai-cms backend (B5 P2.5)",
        f"# Last rebuild: {datetime.now(timezone.utc).isoformat()}",
        f"# Total mappings: {len(items)}",
        "# Format: <domain> <slug>;",
        "",
    ]
    for d, slug in items:
        if d.deleted_at is not None:
            continue
        # map 语法: <key> <value>; (分号是行结束符, 每条映射必须 ; 结束)
        lines.append(f"{d.domain} {slug};")
    lines.append("")
    return "\n".join(lines)


async def rebuild_sites_map(db: AsyncSession) -> int:
    """从 DB 重新生成 sites.map, 返回 mapping 条数.

    容错:
    - NGINX_CONF_DIR 不存在 (单机开发) → 写本地 fallback 路径
    - 写失败 → log + 不抛 (不影响主请求)
    """
    settings = get_settings()
    result = await db.execute(
        select(SiteDomain, Site.slug)
        .join(Site, Site.id == SiteDomain.site_id)
        .where(SiteDomain.deleted_at.is_(None), Site.deleted_at.is_(None))
    )
    rows = result.all()
    # P5: 转为 (domain, slug) 元组, 避免 _format_map 内访问 d.site 触发 lazy IO
    items = [(d, slug) for d, slug in rows if d.deleted_at is None]
    content = _format_map(items)

    target = settings.NGINX_SITES_MAP
    try:
        import os
        import asyncio
        # P5 修复: 原同步 IO 在 async 函数里触发 greenlet 警告,
        # 用 to_thread 隔离. 同步不能直接被 async 函数 await.
        def _write():
            os.makedirs(os.path.dirname(target), exist_ok=True)
            tmp = target + ".tmp"
            with open(tmp, "w", encoding="utf-8") as f:
                f.write(content)
            os.replace(tmp, target)
        await asyncio.to_thread(_write)
        logger.info(f"nginx sites.map rebuilt: {len(items)} mappings → {target}")
        return len(items)
    except Exception as e:
        logger.warning(f"nginx sites.map rebuild failed (non-fatal): {e}")
        return 0


def rebuild_sites_map_sync_fallback() -> int:
    """同步 fallback: 写本地 /tmp/sites.map (用于 lifespan 启动 + 无 db 场景)."""
    settings = get_settings()
    try:
        import os
        os.makedirs(os.path.dirname(settings.NGINX_SITES_MAP), exist_ok=True)
        content = (
            "# B5 fallback: rebuild_sites_map() not called yet\n"
            "# Run lifespan startup to populate from DB\n"
        )
        with open(settings.NGINX_SITES_MAP, "w", encoding="utf-8") as f:
            f.write(content)
        return 0
    except Exception as e:
        logger.warning(f"nginx fallback map init failed: {e}")
        return 0
